In [3]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import time
import datetime as dt
import pymongo
import ast
from config import USER, PASSWORD, CLIENT_ID, CLIENT_SECRET
# Import API key
#from api_keys import CLIENT_ID, CLIENT_SECRET

# CLIENT_ID = "lxOoFeO416HkSlXFiuVTU"
# CLIENT_SECRET = "PWsQxpgJ7G1tgN1wlO0122bPEbOwZiU1g7SCwUBe"

In [4]:
# boundaries
bottom = 25
top = 49
left = -126
right = -66
add_prcp = "&filter=prcp"
add_snow= "&filter=snow"

In [5]:
df_maxtemp = pd.DataFrame([], columns = {'Date','Date(ISO)', 'Lat', 'Long', 'Temp(F)'})
df_mintemp = pd.DataFrame([], columns = {'Date','Date(ISO)', 'Lat', 'Long', 'Temp(F)'})
df_prcp = pd.DataFrame([], columns = {'Date','Date(ISO)', 'Lat', 'Long', 'Prcp(in)'})
df_snow = pd.DataFrame([], columns = {'Date','Date(ISO)', 'Lat', 'Long', 'Snow(in)'})

df_snow = df_snow[['Date','Date(ISO)',  'Lat', 'Long', 'Snow(in)']]
df_prcp = df_prcp[['Date','Date(ISO)',  'Lat', 'Long', 'Prcp(in)']]
df_maxtemp = df_maxtemp[['Date', 'Date(ISO)', 'Lat', 'Long', 'Temp(F)']]
df_mintemp = df_mintemp[['Date', 'Date(ISO)', 'Lat', 'Long', 'Temp(F)']]

height = (top-bottom)/15
width = (right-left)/40

In [ ]:
##MAXTEMP
#for i in range(15):
for i in range(15):
    box_top = round(top - i*height,4)
    box_bottom = round(box_top - height,4)
    #for j in range(40):
    for j in range(40):
        box_left = round(left + j*height,4)
        box_right = round(box_left + width,4)
        
        query_url = f"https://api.aerisapi.com/records/within?format=geojson&p={box_bottom},{box_left},{box_top},{box_right}&limit=2000&from=01/01/1950&to=now&client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&filter=maxt"
        weather_response = requests.get(query_url)
        weather_json = weather_response.json()
        print(i*40+j, len(weather_json['features']), box_bottom, box_left, box_top, box_right)
        for k in range(len(weather_json['features'])):
            response = weather_json['features'][k]

            fahr_temp = response['properties']['report']['details']['tempF']
            lat = response['geometry']['coordinates'][1]
            lon = response['geometry']['coordinates'][0]
            date = response['properties']['report']['timestamp']
            dateiso = response['properties']['report']['dateTimeISO']
            
            df_maxtemp = df_maxtemp.append(pd.Series([date, dateiso, lat, lon, fahr_temp], index=df_maxtemp.columns ), ignore_index=True)

0 239 47.4 -126.0 49.0 -124.5
1 1000 47.4 -124.4 49.0 -122.9
2 1000 47.4 -122.8 49.0 -121.3
3 1000 47.4 -121.2 49.0 -119.7
4 1000 47.4 -119.6 49.0 -118.1
5 1000 47.4 -118.0 49.0 -116.5
6 1000 47.4 -116.4 49.0 -114.9
7 1000 47.4 -114.8 49.0 -113.3
8 1000 47.4 -113.2 49.0 -111.7
9 1000 47.4 -111.6 49.0 -110.1
10 1000 47.4 -110.0 49.0 -108.5

In [6]:
##MINTEMP
#for i in range(15):
for i in range(15):
    box_top = round(top - i*height,4)
    box_bottom = round(box_top - height,4)
    #for j in range(40):
    for j in range(40):
        box_left = round(left + j*height,4)
        box_right = round(box_left + width,4)
        
        query_url = f"https://api.aerisapi.com/records/within?format=geojson&p={box_bottom},{box_left},{box_top},{box_right}&limit=2000&from=01/01/1950&to=now&client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&filter=mint"
        weather_response = requests.get(query_url)
        weather_json = weather_response.json()
        print(i*40+j, len(weather_json['features']), box_bottom, box_left, box_top, box_right)
        for k in range(len(weather_json['features'])):
            response = weather_json['features'][k]

            fahr_temp = response['properties']['report']['details']['tempF']
            lat = response['geometry']['coordinates'][1]
            lon = response['geometry']['coordinates'][0]
            date = response['properties']['report']['timestamp']
            dateiso = response['properties']['report']['dateTimeISO']
            
            df_mintemp = df_mintemp.append(pd.Series([date, dateiso, lat, lon, fahr_temp], index=df_mintemp.columns ), ignore_index=True)

0 157 47.4 -126.0 49.0 -124.5
1 1000 47.4 -124.4 49.0 -122.9
2 1000 47.4 -122.8 49.0 -121.3
3 1000 47.4 -121.2 49.0 -119.7
4 1000 47.4 -119.6 49.0 -118.1
5 1000 47.4 -118.0 49.0 -116.5
6 1000 47.4 -116.4 49.0 -114.9
7 1000 47.4 -114.8 49.0 -113.3
8 1000 47.4 -113.2 49.0 -111.7
9 1000 47.4 -111.6 49.0 -110.1
10 1000 47.4 -110.0 49.0 -108.5
11 1000 47.4 -108.4 49.0 -106.9
12 1000 47.4 -106.8 49.0 -105.3
13 1000 47.4 -105.2 49.0 -103.7
14 1000 47.4 -103.6 49.0 -102.1
15 1000 47.4 -102.0 49.0 -100.5
16 1000 47.4 -100.4 49.0 -98.9
17 1000 47.4 -98.8 49.0 -97.3
18 1000 47.4 -97.2 49.0 -95.7
19 1000 47.4 -95.6 49.0 -94.1
20 1000 47.4 -94.0 49.0 -92.5
21 1000 47.4 -92.4 49.0 -90.9
22 1000 47.4 -90.8 49.0 -89.3
23 316 47.4 -89.2 49.0 -87.7
24 0 47.4 -87.6 49.0 -86.1
25 0 47.4 -86.0 49.0 -84.5
26 0 47.4 -84.4 49.0 -82.9
27 0 47.4 -82.8 49.0 -81.3
28 0 47.4 -81.2 49.0 -79.7
29 0 47.4 -79.6 49.0 -78.1
30 0 47.4 -78.0 49.0 -76.5
31 0 47.4 -76.4 49.0 -74.9
32 0 47.4 -74.8 49.0 -73.3
33 0 47.4 -73.2 49.0 -71.7
34 0 47.4 -71.6 49.0 -70.1
35 0 47.4 -70.0 49.0 -68.5
36 0 47.4 -68.4 49.0 -66.9
37 0 47.4 -66.8 49.0 -65.3
38 0 47.4 -65.2 49.0 -63.7
39 0 47.4 -63.6 49.0 -62.1
40 0 45.8 -126.0 47.4 -124.5
41 1000 45.8 -124.4 47.4 -122.9
42 1000 45.8 -122.8 47.4 -121.3
43 1000 45.8 -121.2 47.4 -119.7

KeyboardInterrupt:

In [86]:
##PRCP
#for i in range(15):
for i in range(3):
    box_top = round(top - i*height,4)
    box_bottom = round(box_top - height,4)
    #for j in range(40):
    for j in range(3):
        box_left = round(left + j*height,4)
        box_right = round(box_left + width,4)
        
        query_url = f"https://api.aerisapi.com/records/within?format=geojson&p={box_bottom},{box_left},{box_top},{box_right}&limit=2000&from=01/01/2000&to=now&client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&filter=prcp"
        weather_response = requests.get(query_url)
        weather_json = weather_response.json()
        print(i*40+j, len(weather_json['features']), box_bottom, box_left, box_top, box_right)
        for k in range(len(weather_json['features'])):
            
            response = weather_json['features'][k]

            prcp = response['properties']['report']['details']['prcpIN']
            lat = response['geometry']['coordinates'][1]
            lon = response['geometry']['coordinates'][0]
            date = response['properties']['report']['timestamp']
            dateiso = response['properties']['report']['dateTimeISO']
            
            df_prcp = df_prcp.append(pd.Series([date, dateiso, lat, lon, prcp], index=df_prcp.columns ), ignore_index=True)

0 158 47.4 -126.0 49.0 -124.5
1 358 47.4 -124.4 49.0 -122.9
2 1000 47.4 -122.8 49.0 -121.3
40 0 45.8 -126.0 47.4 -124.5
41 1000 45.8 -124.4 47.4 -122.9
42 1000 45.8 -122.8 47.4 -121.3
80 0 44.2 -126.0 45.8 -124.5
81 1000 44.2 -124.4 45.8 -122.9
82 1000 44.2 -122.8 45.8 -121.3

In [87]:
##SNOW
#for i in range(15):
for i in range(3):
    box_top = round(top - i*height,4)
    box_bottom = round(box_top - height,4)
    #for j in range(40):
    for j in range(3):
        box_left = round(left + j*height,4)
        box_right = round(box_left + width,4)
        
        query_url = f"https://api.aerisapi.com/records/within?format=geojson&p={box_bottom},{box_left},{box_top},{box_right}&limit=2000&from=01/01/2000&to=now&client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&filter=snow"
        weather_response = requests.get(query_url)
        weather_json = weather_response.json()
        print(i*40+j, len(weather_json['features']), box_bottom, box_left, box_top, box_right)
        for k in range(len(weather_json['features'])):
            response = weather_json['features'][k]

            snow = response['properties']['report']['details']['snowIN']
            lat = response['geometry']['coordinates'][1]
            lon = response['geometry']['coordinates'][0]
            date = response['properties']['report']['timestamp']
            dateiso = response['properties']['report']['dateTimeISO']
            
            df_snow = df_snow.append(pd.Series([date, dateiso lat, lon, snow], index=df_snow.columns ), ignore_index=True)

0 1 47.4 -126.0 49.0 -124.5
1 60 47.4 -124.4 49.0 -122.9
2 499 47.4 -122.8 49.0 -121.3
40 0 45.8 -126.0 47.4 -124.5
41 128 45.8 -124.4 47.4 -122.9
42 515 45.8 -122.8 47.4 -121.3
80 0 44.2 -126.0 45.8 -124.5
81 222 44.2 -124.4 45.8 -122.9
82 582 44.2 -122.8 45.8 -121.3

In [16]:

query_url = f"https://api.aerisapi.com/records/within?p={box_bottom},{box_left},{box_top},{box_right}&limit=2000&from=01/01/2000&to=now&client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&filter=maxt"
weather_response = requests.get(query_url)
weather_json = weather_response.json()

In [ ]:
conn = f'mongodb+srv://admin:password2@weatherviz-andy-5dubo.mongodb.net/weatherviz?retryWrites=true'
client = pymongo.MongoClient(conn)
db = client.weatherviz
mint_json = df_mintemp.to_json()


db.min_temp.insert_one(ast.literal_eval(mint_json))

Empty DataFrame
Columns: [Date, Date(ISO), Lat, Long, Temp(F)]
Index: []

TypeError: strptime() takes exactly 2 arguments (1 given)

In [16]:
response

{'type': 'Feature',
 'id': '5c1bf4c66bcc5a20c9ce69e0',
 'geometry': {'type': 'Point', 'coordinates': [-124.555, 47.9375]},
 'properties': {'id': '5c1bf4c66bcc5a20c9ce69e0',
  'loc': {'long': -124.555, 'lat': 47.9375},
  'report': {'timestamp': 1544774400,
   'dateTimeISO': '2018-12-14T00:00:00-08:00',
   'code': 3,
   'type': 'maxt',
   'station': {'id': 'USW00094240',
    'type': None,
    'name': 'quillayute state airport'},
   'location': 'quillayute state airport',
   'details': {'text': '13.3', 'tempC': 13.3, 'tempF': 55.9},
   'tied': False,
   'prev': {'timestamp': 1039852800,
    'dateTimeISO': '2002-12-14T00:00:00-08:00',
    'details': {'text': '12.8', 'tempC': 12.8, 'tempF': 55}}},
  'place': {'name': 'quillayute state ap', 'state': 'wa', 'country': 'us'},
  'profile': {'tz': 'America/Los_Angeles'}}}

In [17]:
fahr_temp = response['properties']['report']['details']['tempF']
lat = response['geometry']['coordinates'][1]
lon = response['geometry']['coordinates'][0]
date = response['properties']['report']['timestamp']
dateiso = response['properties']['report']['dateTimeISO']

fahr_temp, lat, lon, date, dateiso

(55.9, 47.9375, -124.555, 1544774400, '2018-12-14T00:00:00-08:00')

In [23]:
df_maxtemp

             Date                  Date(ISO)      Lat      Long  Temp(F)
0      1544774400  2018-12-14T00:00:00-08:00  47.9375 -124.5550     55.9
1      1539763200  2018-10-17T01:00:00-07:00  47.9375 -124.5550     73.9
2      1539676800  2018-10-16T01:00:00-07:00  47.9375 -124.5550     80.1
3      1539590400  2018-10-15T01:00:00-07:00  47.9375 -124.5550     73.9
4      1524556800  2018-04-24T01:00:00-07:00  47.9375 -124.5550     75.9
5      1516003200  2018-01-15T00:00:00-08:00  47.9375 -124.5550     63.0
6      1515916800  2018-01-14T00:00:00-08:00  47.9375 -124.5550     57.9
7      1512892800  2017-12-10T00:00:00-08:00  47.9375 -124.5550     59.0
8      1511337600  2017-11-22T00:00:00-08:00  47.9375 -124.5550     57.9
9      1504425600  2017-09-03T01:00:00-07:00  47.9375 -124.5550     88.0
10     1503907200  2017-08-28T01:00:00-07:00  47.9375 -124.5550     91.9
11     1503820800  2017-08-27T01:00:00-07:00  47.9375 -124.5550     91.0
12     1501660800  2017-08-02T01:00:00-07:00  47.9375 -124.5550     98.1
13     1501574400  2017-08-01T01:00:00-07:00  47.9375 -124.5550     90.0
14     1498377600  2017-06-25T01:00:00-07:00  47.9375 -124.5550     86.0
15     1498291200  2017-06-24T01:00:00-07:00  47.9375 -124.5550     91.9
16     1478592000  2016-11-08T00:00:00-08:00  47.9375 -124.5550     63.0
17     1478505600  2016-11-07T00:00:00-08:00  47.9375 -124.5550     64.0
18     1472198400  2016-08-26T01:00:00-07:00  47.9375 -124.5550     86.0
19     1472112000  2016-08-25T01:00:00-07:00  47.9375 -124.5550     91.9
20     1472025600  2016-08-24T01:00:00-07:00  47.9375 -124.5550     91.0
21     1471680000  2016-08-20T01:00:00-07:00  47.9375 -124.5550     86.0
22     1471593600  2016-08-19T01:00:00-07:00  47.9375 -124.5550     96.1
23     1471507200  2016-08-18T01:00:00-07:00  47.9375 -124.5550     96.1
24     1465027200  2016-06-04T01:00:00-07:00  47.9375 -124.5550     90.0
25     1463126400  2016-05-13T01:00:00-07:00  47.9375 -124.5550     80.1
26     1462176000  2016-05-02T01:00:00-07:00  47.9375 -124.5550     81.0
27     1461052800  2016-04-19T01:00:00-07:00  47.9375 -124.5550     75.9
28     1460966400  2016-04-18T01:00:00-07:00  47.9375 -124.5550     80.1
29     1460880000  2016-04-17T01:00:00-07:00  47.9375 -124.5550     77.0
...           ...                        ...      ...       ...      ...
14209   859874400  1997-04-01T00:00:00-06:00  47.8038 -103.2891     75.0
14210   859874400  1997-04-01T00:00:00-06:00  48.4564 -102.5947     66.0
14211   859356000  1997-03-26T00:00:00-06:00  47.8966 -102.9208     66.9
14212   859356000  1997-03-26T00:00:00-06:00  47.6000 -103.2597     73.9
14213   852098400  1997-01-01T00:00:00-06:00  47.8966 -102.9208     42.1
14214   852098400  1997-01-01T00:00:00-06:00  48.6630 -103.2130     39.9
14215   844581600  1996-10-06T01:00:00-05:00  48.3988 -102.9180     77.0
14216   840952800  1996-08-25T01:00:00-05:00  47.6000 -103.2597    100.9
14217   840348000  1996-08-18T01:00:00-05:00  47.8038 -103.2891    100.9
14218   840348000  1996-08-18T01:00:00-05:00  48.3988 -102.9180     98.1
14219   840348000  1996-08-18T01:00:00-05:00  48.4564 -102.5947    100.9
14220   834300000  1996-06-09T01:00:00-05:00  47.8966 -102.9208     95.0
14221   834300000  1996-06-09T01:00:00-05:00  48.6630 -103.2130     96.1
14222   834300000  1996-06-09T01:00:00-05:00  48.5722 -102.6466     98.1
14223   834300000  1996-06-09T01:00:00-05:00  48.7994 -102.2463     98.1
14224   834213600  1996-06-08T01:00:00-05:00  48.5722 -102.6466     93.9
14225   826956000  1996-03-16T00:00:00-06:00  47.8038 -103.2891     66.0
14226   826956000  1996-03-16T00:00:00-06:00  48.3988 -102.9180     57.9
14227   826869600  1996-03-15T00:00:00-06:00  48.6630 -103.2130     59.0
14228   826610400  1996-03-12T00:00:00-06:00  47.8038 -103.2891     61.0
14229   823932000  1996-02-10T00:00:00-06:00  47.8038 -103.2891     48.9
14230   823845600  1996-02-09T00:00:00-06:00  47.8038 -103.2891     48.0
14231   823845600  1996-02-09T00:00:00-06:00  47.6000 -103.2597     57.0
14232   823845600  1996-02-09T00:00:00-06:00  48.7994 -102.2463     48.9
14233   821512800  1996-01-13T00:00:00-06:00  47.8966 -102.9208     46.0
14234   821512800  1996-01-13T00:00:00-06:00  47.8038 -103.2891     48.0
14235   821512800  1996-01-13T00:00:00-06:00  47.6000 -103.2597     54.0
14236   821426400  1996-01-12T00:00:00-06:00  47.6000 -103.2597     55.0
14237   821426400  1996-01-12T00:00:00-06:00  48.9075 -103.2936     46.9
14238   817711200  1995-11-30T00:00:00-06:00  47.6000 -103.2597     55.0

[14239 rows x 5 columns]